### ISSUE TITLE
BlockVisibilityParameter Cant be found

### ISSUE THREAD

**Issue by totalfit1544** [nanoLogika/ACadSvg#84]
Hi Trying to run your project from all the source but always have this error

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0246	The type or namespace name 'BlockVisibilityParameter' could not be found (are you missing a using directive or an assembly reference?)	ACadSvg	D:\Code\_Sample Projects\CAD Programs\ACadSvgStudio-0.3.0_Demo\ACadSvg-main\ACadSvg\BlockRecordSvg.cs	82

**Comment by mme1950** [comment]
Fine that try to use our DWG to SVG.

The classes `BlockVisibilityParameter`, `EvaluationGraph` represent AutoCAD objects related to dynamic blocks.
We implemented theses classes and the respective reader methods and issued a PR to DomCR/ACadSharp. This is, however, not yet merged.
You should be able to get rid of this problem with our forked version of ACadSharp, in particular this branch:
https://github.com/nanoLogika/ACadSharp/tree/7-merged-branch-for-acadsvg.
We will create a new release shortly.

**Comment by mme1950** [comment]
see https://github.com/DomCR/ACadSharp/pull/419
