### ISSUE TITLE
Spline entity: Implement B-Spline with more than four control points.

### ISSUE THREAD

**Issue by mme1950** [nanoLogika/ACadSvg#9]

**Comment by timmwille** [comment]
You might find some hint here to solve this:
https://wiki.freecad.org/B-Splines

or via LibreCAD.org

**Comment by timmwille** [comment]
Also further readings you can find via FreeCAD Forum:
https://forum.freecad.org/viewtopic.php?f=9&t=71130

oder im Code:
https://github.com/search?q=repo%3AAjinkyaDahale%2FFreeCAD%20b-spline&type=code

in the Opencascade CAD Kernel it is implemented as follows, not sure how that helps in this case:
https://dev.opencascade.org/doc/occt-7.6.0/refman/html/class_geom___bezier_curve.html

**Comment by mme1950** [comment]
Found simple C# example here:
https://www.codeproject.com/Articles/1095142/Generate-and-understand-NURBS-curves
